[package]
name = "tp-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
