// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchTask = { description?: string, importance?: number | null, urgency?: number | null, due_date?: string | null, do_date?: string | null, category?: number | null, };
