//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "task")]
#[ts(export)]
#[ts(export_to = "TaskModel.ts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub done: bool,
    pub description: String,
    #[sea_orm(column_type = "Float", nullable)]
    pub importance: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub urgency: Option<f32>,
    pub due_date: Option<DateTimeUtc>,
    pub do_date: Option<DateTimeUtc>,
    pub category: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::Category",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Category,
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
